### PR TITLE
0.5port

### PR DESCRIPTION
**Pull request by lbondaryk**
This is all the css and multiple choice updates - @mlippert please take a look to see if this could be rolled to Master. Note, this is off BricLayer work and depends upon that.

### CODE REVIEW

**Comment by mlippert** [comment]
Overall this looks good. I've got some small changes and have also added the fix for the 918 issue caused by the Chrome update to Mac and Windows. This was breaking unit tests also, so I've made the necessary changes so that the unit tests pass. See my commits which follow.

**Comment by mlippert** [comment]
:+1:  go ahead and merge it into master as it stands now.

**Comment by mlippert** [comment]
:+1: still good, merge it to master (use the green merge pull button :smiley:)

**Comment by lbondaryk** [comment]
I merged to master, but I'm not done with this branch yet, because I'm not done with the port yet.  Also, some horrible things happened when I tried to pull in your changes on top of mine, and I'm still resolving.

**Pull request merged**
