### PR TITLE
350 hilight mortar (briclayer support for brix-topic dynamic value)

### PR DESCRIPTION
**Pull request by mlippert**
These changes are to implement the briclayer support for the brix-topic dynamic value type.

This is needced to more easily specify the topic that the hilite mortar should subscribe to. It also required adding support the the brix types that need to supply the topic, namely implementing a static class method getEventTopic.

### CODE REVIEW

**Comment by mlippert** [comment]
@ysahnpark, @seannives, @lbondaryk  this story branch is ready to be code reviewed.

The NeffReactor utilizes the new functionality in the briclayer. This was just a new dynamic value type 'brix-topic' which gets the event topic that an instance of a bric type with a given instance ID will use for a particular named event. For example the 'selected' event is published by the LabelGroup and if I create a LabelGroup w/ an id of `"foo"`, it will publish the 'selected' event using a topic of `"foo_labelSelected"`.

It required support in the `BricWorks` as well as by bric types whose event topics are needed. Currently in order to implement NeffReactor this was the `Callouts` and the `LabelGroup`, although I implemented support in a couple of other bric types as well.

The new functionality in the `BricWorks` and in the `BricLayer` is being unit tested (I also enhanced the testing of the other dynamic value types supported by the `BricLayer`).

**Comment by mlippert** [comment]
IRC conversation between @ysahnpark and @mlippert that seems generally useful, so it's been copied below.

[10:57:12] **youn-suk:** Mike, Initially when I first went through the config in NeffReactor, I though that the instanceId was used to retrieve the actual brix instance and invoke on a method that returns the topic. Now that see your BrixWorks code, I realized that you are using the brixType as well and calling a static method. And your explanation in pull request made sense.
[10:59:59] **mikel:** ok good. thanks for reviewing. who knows when I might have noticed the missing references in the json schema
[11:00:16] **youn-suk:** Out of curiosity, if we have the brix instanceId, isnt't it possible to get the brix instance and an instance method (and not need to pass the brixType along)?
[11:01:37] **youn-suk:** One reason I can think of is that it allows for uninstantiated brix...
[11:02:01] **mikel:** well, those brix whose topic I'm getting are in different containers and in half the cases they haven't been created yet so...
[11:03:21] **mikel:** the only way to do what you're saying is to use that invoker class and do some special fixup in each container AFTER there is another notification that all containers have been initialized.
[11:03:58] **mikel:** so it's possible but it requires a lot of work to create the infrastructure. I'm hoping this shortcut is sufficient.
[11:04:55] **mikel:** It's a solution partway between that full-blown get the value from the instance, and your earlier suggestion that every topic be easily constructed from known strings.
[11:05:57] **mikel:** actually we should probably have this conversation in the main irc, I suspect seann and leslie may want to see some of it.
[11:09:12] **young-suk:** OK, for the mean time, I just mention it in the pull request comment.
[11:09:42] **mikel:** ah, that's a good idea, I'll copy this conversation there.

**Comment by ysahnpark** [comment]
The code looks good.

Just few comments:
- Reference to "dynamicValue-brix-topic" the BrixActivityConfigSchema.json
- Could you put double quotes around the property names on:
  https://github.com/lbondaryk/PlayerProto/blob/350-Hilight-mortar/NeffReactor.html#L251, (so it makes me easy reuse it)
- Also change tabs to spaces, it would make it easier to review on GitHub.
- Tab to spaces on BrixActivityConfigSchema.json too =)

Design Decision rationale:
The current code is using a static method on each Brix class to obtain the topic. The reason is because the scope that the topic is being used may not include the brix instance. E.g. Brix in different IPC in iframe mode.
Otherwise an instance method could be used (possibly at base class level), and avoid sending the BrixType.

**Comment by mlippert** [comment]
@ysahnpark I think I've addressed all your points. Thanks. If you agree, would you give the pull request a thumbs up?

**Comment by ysahnpark** [comment]
:+1:

**Pull request merged**
