### PR TITLE
1330 journal brix

### PR DESCRIPTION
**Pull request by seannives**
@mlippert, @lbondaryk, and @ysahnpark - please code review.

### CODE REVIEW

**Comment by lbondaryk** [comment]
Don't suppose you'd care to make a page in the demo book for this?

**Comment by seannives** [comment]
Demo book page added.

**Comment by mlippert** [comment]
- I see you added `answerKey-journal` to the activity config schema, which is good, I've been forgetting to add some things there. However you don't reference it. It should be referenced in the `brixConfig` definitition's `answerKey` property by adding it to the `oneOf` section.
- I started putting the following lines in the template right after the activity config is defined and before creating the event manager:

```
// turn on logging to make it easier to debug what's happening when making changes
pearson.utils.logToConsole(true, 'FINER', 'pearson');
```

instead of the 3 lines of script that define the debugConsole and set the logger output level that are in the Template_Journal...
- Journal.toggleEnabler looks like an abandoned method that should be removed.
  -The logger already reports the loggername, ie pearson.brix.Journal so a prefix of 'Journal:' is not as helpful as it was when that was all that was written to the console.
  -In general I don't think we want to set id's on the elements we create. Keeping a pointer to the top containing element along w/ knowing the structure and classes assigned under that element should be sufficient for anything we need to do.
  -In general we probably want to continue to use d3 selections and events rather than some other library since most brix are already heavily dependent on d3. I don't know if that applies to the goog.events.KeyHandler you might have been able to do:

``` javascript
textentry.on('keypress', function () {that.submitButton.setEnabled(true);});
```

however even if you need to use the goog.events.KeyHandler I would get the textArea element by:

``` javascript
var textArea = textentry.node();
```
- And I'm not sure about the pact to totally skip unit tests. At least create the skeleton spec file and include it in the index.html with a top level describe and perhaps 1 skipped 'it should...' (Oh I missed that you split the unit tests off to ECOURSES-1741)

**Comment by seannives** [comment]
This still has some work but I'm merging it into master because we're not using journal brix for anything immediately and I don't want the branch to get too stale.

**Pull request merged**
